using AIDevelopmentEasy.Api.Models;
using AIDevelopmentEasy.Core.Models;

namespace AIDevelopmentEasy.Api.Repositories.Interfaces;

/// <summary>
/// Repository interface for requirement operations.
/// Manages requirements and their wizard state.
/// </summary>
public interface IRequirementRepository
{
    /// <summary>
    /// Get all requirements
    /// </summary>
    Task<IEnumerable<RequirementDto>> GetAllAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Get a single requirement by ID
    /// </summary>
    Task<RequirementDetailDto?> GetByIdAsync(string id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Create a new requirement
    /// </summary>
    Task<RequirementDto> CreateAsync(CreateRequirementRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Update a requirement
    /// </summary>
    Task<RequirementDto?> UpdateAsync(string id, UpdateRequirementRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Delete a requirement
    /// </summary>
    Task<bool> DeleteAsync(string id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Check if requirement exists
    /// </summary>
    Task<bool> ExistsAsync(string id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get the full requirement entity (internal use)
    /// </summary>
    Task<Requirement?> GetEntityAsync(string id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Save the full requirement entity (internal use)
    /// </summary>
    Task SaveEntityAsync(Requirement requirement, CancellationToken cancellationToken = default);

    // ═══════════════════════════════════════════════════════════════════════════════
    // Wizard State Operations
    // ═══════════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Update requirement status
    /// </summary>
    Task UpdateStatusAsync(string id, RequirementStatusDto status, CancellationToken cancellationToken = default);

    /// <summary>
    /// Update wizard phase
    /// </summary>
    Task UpdatePhaseAsync(string id, WizardPhaseDto phase, CancellationToken cancellationToken = default);

    /// <summary>
    /// Save questions generated by LLM
    /// </summary>
    Task SaveQuestionsAsync(string id, QuestionSetDto questions, CancellationToken cancellationToken = default);

    /// <summary>
    /// Save user's answers
    /// </summary>
    Task SaveAnswersAsync(string id, AnswerSetDto answers, string? aiNotes, CancellationToken cancellationToken = default);

    /// <summary>
    /// Save final refined requirement content
    /// </summary>
    Task SaveFinalContentAsync(string id, string finalContent, CancellationToken cancellationToken = default);

    /// <summary>
    /// Save generated stories from decomposition
    /// </summary>
    Task SaveGeneratedStoriesAsync(string id, List<StoryDefinitionDto> stories, CancellationToken cancellationToken = default);

    /// <summary>
    /// Add created story ID to requirement
    /// </summary>
    Task AddCreatedStoryIdAsync(string id, string storyId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get stories linked to this requirement
    /// </summary>
    Task<IEnumerable<string>> GetCreatedStoryIdsAsync(string id, CancellationToken cancellationToken = default);

    // ═══════════════════════════════════════════════════════════════════════════════
    // Wizard History Operations
    // ═══════════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Save wizard status/history
    /// </summary>
    Task SaveWizardStatusAsync(string id, WizardStatusDto status, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get wizard status/history
    /// </summary>
    Task<WizardStatusDto?> GetWizardStatusAsync(string id, CancellationToken cancellationToken = default);
}
