namespace AIDevelopmentEasy.Core.Models;

/// <summary>
/// Requirement entity - top level container created through the wizard
/// </summary>
public class Requirement
{
    /// <summary>
    /// Unique identifier (e.g., "REQ-001")
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable title
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Raw requirement text as entered by user
    /// </summary>
    public string RawContent { get; set; } = string.Empty;

    /// <summary>
    /// Refined/final requirement document after wizard completion
    /// </summary>
    public string? FinalContent { get; set; }

    /// <summary>
    /// Type of requirement
    /// </summary>
    public RequirementType Type { get; set; }

    /// <summary>
    /// Current status
    /// </summary>
    public RequirementStatus Status { get; set; } = RequirementStatus.Draft;

    /// <summary>
    /// Current wizard phase
    /// </summary>
    public WizardPhase CurrentPhase { get; set; } = WizardPhase.Input;

    /// <summary>
    /// Questions generated by LLM
    /// </summary>
    public QuestionSet? Questions { get; set; }

    /// <summary>
    /// User's answers to questions
    /// </summary>
    public AnswerSet? Answers { get; set; }

    /// <summary>
    /// Additional notes from user for AI
    /// </summary>
    public string? AiNotes { get; set; }

    /// <summary>
    /// Generated stories from decomposition
    /// </summary>
    public List<StoryDefinition> GeneratedStories { get; set; } = new();

    /// <summary>
    /// IDs of created stories (after approval)
    /// </summary>
    public List<string> CreatedStoryIds { get; set; } = new();

    /// <summary>
    /// Associated codebase ID (optional)
    /// </summary>
    public string? CodebaseId { get; set; }

    /// <summary>
    /// Creation timestamp
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Last update timestamp
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Completion timestamp
    /// </summary>
    public DateTime? CompletedAt { get; set; }
}

/// <summary>
/// Requirement type classification
/// </summary>
public enum RequirementType
{
    /// <summary>New feature development</summary>
    Feature,

    /// <summary>Enhancement to existing functionality</summary>
    Improvement,

    /// <summary>Bug fix or defect correction</summary>
    Defect,

    /// <summary>Technical debt or refactoring</summary>
    TechDebt
}

/// <summary>
/// Requirement lifecycle status
/// </summary>
public enum RequirementStatus
{
    /// <summary>Initial draft, not yet processed</summary>
    Draft,

    /// <summary>Wizard is in progress</summary>
    InProgress,

    /// <summary>Wizard completed, stories created</summary>
    Completed,

    /// <summary>Wizard was cancelled</summary>
    Cancelled,

    /// <summary>Wizard failed with error</summary>
    Failed
}

/// <summary>
/// Wizard phase enumeration
/// </summary>
public enum WizardPhase
{
    /// <summary>Phase 1: Initial input (raw text + type)</summary>
    Input,

    /// <summary>Phase 2: LLM analyzing and generating questions</summary>
    Analysis,

    /// <summary>Phase 3: User answering questions</summary>
    Questions,

    /// <summary>Phase 4: LLM refining requirement with answers</summary>
    Refinement,

    /// <summary>Phase 5: LLM decomposing into stories</summary>
    Decomposition,

    /// <summary>Phase 6: User reviewing and selecting stories</summary>
    Review,

    /// <summary>Phase 7: Completed</summary>
    Completed
}

/// <summary>
/// State of a wizard phase
/// </summary>
public enum WizardPhaseState
{
    /// <summary>Not yet started</summary>
    Pending,

    /// <summary>Currently running (LLM processing)</summary>
    Running,

    /// <summary>Waiting for user approval/input</summary>
    WaitingApproval,

    /// <summary>Successfully completed</summary>
    Completed,

    /// <summary>Failed with error</summary>
    Failed,

    /// <summary>Skipped</summary>
    Skipped
}

/// <summary>
/// Set of questions generated by LLM
/// </summary>
public class QuestionSet
{
    /// <summary>
    /// List of questions
    /// </summary>
    public List<Question> Questions { get; set; } = new();
}

/// <summary>
/// A single question
/// </summary>
public class Question
{
    /// <summary>
    /// Question identifier (e.g., "Q1")
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Category of the question
    /// </summary>
    public QuestionCategory Category { get; set; }

    /// <summary>
    /// Question text
    /// </summary>
    public string Text { get; set; } = string.Empty;

    /// <summary>
    /// Type of input expected
    /// </summary>
    public QuestionType Type { get; set; }

    /// <summary>
    /// Available options for single/multiple choice
    /// </summary>
    public List<string> Options { get; set; } = new();

    /// <summary>
    /// Whether this question must be answered
    /// </summary>
    public bool Required { get; set; } = true;

    /// <summary>
    /// Context explaining why this information is needed
    /// </summary>
    public string? Context { get; set; }
}

/// <summary>
/// Question category
/// </summary>
public enum QuestionCategory
{
    Functional,
    NonFunctional,
    Technical,
    Business,
    UX
}

/// <summary>
/// Question input type
/// </summary>
public enum QuestionType
{
    /// <summary>Single selection (radio buttons)</summary>
    Single,

    /// <summary>Multiple selection (checkboxes)</summary>
    Multiple,

    /// <summary>Free text input</summary>
    Text
}

/// <summary>
/// Set of answers from user
/// </summary>
public class AnswerSet
{
    /// <summary>
    /// List of answers
    /// </summary>
    public List<Answer> Answers { get; set; } = new();
}

/// <summary>
/// A single answer
/// </summary>
public class Answer
{
    /// <summary>
    /// Question ID this answers
    /// </summary>
    public string QuestionId { get; set; } = string.Empty;

    /// <summary>
    /// Selected options (for single/multiple choice)
    /// </summary>
    public List<string> SelectedOptions { get; set; } = new();

    /// <summary>
    /// Text response (for text type questions)
    /// </summary>
    public string? TextResponse { get; set; }
}

/// <summary>
/// Story definition generated from decomposition
/// </summary>
public class StoryDefinition
{
    /// <summary>
    /// Story identifier (e.g., "STR-1")
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Story title
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Acceptance criteria
    /// </summary>
    public List<string> AcceptanceCriteria { get; set; } = new();

    /// <summary>
    /// Estimated complexity
    /// </summary>
    public StoryComplexity EstimatedComplexity { get; set; }

    /// <summary>
    /// Dependencies on other stories
    /// </summary>
    public List<string> Dependencies { get; set; } = new();

    /// <summary>
    /// Technical implementation notes
    /// </summary>
    public string? TechnicalNotes { get; set; }

    /// <summary>
    /// Whether user selected this story for creation
    /// </summary>
    public bool Selected { get; set; } = true;
}

/// <summary>
/// Story complexity estimation
/// </summary>
public enum StoryComplexity
{
    Small,
    Medium,
    Large
}

/// <summary>
/// Wizard execution status
/// </summary>
public class WizardStatus
{
    /// <summary>
    /// Requirement ID
    /// </summary>
    public string RequirementId { get; set; } = string.Empty;

    /// <summary>
    /// Current phase
    /// </summary>
    public WizardPhase CurrentPhase { get; set; }

    /// <summary>
    /// Whether wizard is actively running
    /// </summary>
    public bool IsRunning { get; set; }

    /// <summary>
    /// Status of each phase
    /// </summary>
    public List<WizardPhaseStatus> Phases { get; set; } = new();

    /// <summary>
    /// Start timestamp
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Completion timestamp
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Error message if failed
    /// </summary>
    public string? Error { get; set; }
}

/// <summary>
/// Status of a single wizard phase
/// </summary>
public class WizardPhaseStatus
{
    /// <summary>
    /// Phase identifier
    /// </summary>
    public WizardPhase Phase { get; set; }

    /// <summary>
    /// Current state
    /// </summary>
    public WizardPhaseState State { get; set; }

    /// <summary>
    /// Status message
    /// </summary>
    public string? Message { get; set; }

    /// <summary>
    /// Start timestamp
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Completion timestamp
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Phase-specific result data
    /// </summary>
    public object? Result { get; set; }
}
